
services:
  redis:
    image: redis:7
    container_name: karnet-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: karnet-redisinsight
    ports:
      - "5540:5540"
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - REDISINSIGHT_REDIS_HOSTS=redis:6379

